---
#- name: pipework an IP address for compass-cobbler
#  command: "pipework {{ install_net }} compass-cobbler {{ install_ip }}/{{ install_prefix }}"

- name: run cobbler start.sh
  command: docker exec -it compass-cobbler /usr/local/bin/start.sh
