---
- name: get jumphost ip
  shell: |
    external_nic=`ip route |grep '^default'|awk '{print $5F}'`
    host_ip=`ifconfig $external_nic | grep 'inet addr:' | cut -d: -f2 | awk '{ print $1}'`
    echo $host_ip
  register: external_ip

- name: fix name.service
  shell: |
    if [ ! -f "/etc/apparmor.d/usr.sbin.named" ]; then
    ln -s /etc/apparmor.d/usr.sbin.named /etc/apparmor.d/disable/
    apparmor_parser -R /etc/apparmor.d/usr.sbin.named
    fi

- name: render docker-compose file
  template:
    src: docker-compose.yml.j2
    dest: "{{ docker_compose_dir }}/docker-compose.yml"
    owner: root
    group: root
    mode: 0644

- name: docker-compose down
  shell: docker-compose down
  args:
    chdir: "{{ docker_compose_dir }}"

- name: load docker images
  shell: |
    docker load -i "{{ compass_dists_dir }}/{{ item.split('/')[1].split(':')[0] }}.tar"
  with_items:
    - "{{ compass_deck }}"
    - "{{ compass_tasks }}"
    - "{{ compass_cobbler }}"
    - "{{ compass_db }}"
    - "{{ compass_mq }}"

- name: copy files
  shell:
    cp -rf "{{ item }}" "{{ docker_compose_dir }}"
  with_items:
    - "{{ compass_dir }}/deploy/adapters/ansible"
    - "{{ compass_dir }}/deploy/compass_conf"
    - "{{ compass_dir }}/deploy/adapters/cobbler"

- name: create run dir
  file:
    path: "{{ docker_compose_dir }}/ansible/run"
    state: directory
    mode: 0644

- name: render cobbler
  template:
    src: "{{ item }}.j2"
    dest: "{{ docker_compose_dir }}/compass_conf/os_installer/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - cobbler.conf

- name: docker-compose up
  shell: docker-compose up -d
  args:
    chdir: "{{ docker_compose_dir }}"

- name: create compass db tables
  shell: |
    sleep 3; \
    docker exec compass-deck bash -c "/opt/compass/bin/manage_db.py createdb"
  tags:
    - redploy

- name: add ansible callback
  shell: |
    docker cp "{{ item }}" \
    compass-deck:/root/compass-deck/bin/ansible_callbacks
    docker cp "{{ item }}" \
    compass-tasks:/opt/ansible_callbacks
  with_items:
    - "{{ compass_dir }}/deploy/status_callback.py"
    - "{{ compass_dir }}/deploy/playbook_done.py"

- name: rm ansible run
  shell: |
    docker exec compass-tasks bash -c "rm -rf /var/ansible/run/*"

