---
- name: get jumphost ip
  shell: |
    external_nic=`ip route |grep '^default'|awk '{print $5F}'`
    host_ip=`ifconfig $external_nic | grep 'inet addr:' | cut -d: -f2 | awk '{ print $1}'`
    echo $host_ip
  register: external_ip

- name: render docker-compose file
  template:
    src: docker-compose.yml.j2
    dest: "{{ docker_compose_dir }}/docker-compose.yml"
    owner: root
    group: root
    mode: 0644

- name: docker-compose down
  shell: docker-compose down
  args:
    chdir: "{{ docker_compose_dir }}"

- name: load docker images
  shell: |
    docker load -i "{{ compass_dists_dir }}/{{ item }}"
  with_items:
    - compass-deck.tar
    - compass-tasks.tar
    - compass-cobbler.tar
    - compass-db.tar
    - compass-mq.tar

- name: create dir
  file:
    path: "{{ docker_compose_dir }}/{{ item }}"
    state: directory
    mode: 0644
  with_items:
    - ansible
    - os_installer

- name: render cobbler
  template:
    src: "{{ item }}.j2"
    dest: "{{ docker_compose_dir }}/os_installer/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - cobbler.conf

- name: docker-compose up
  shell: docker-compose up -d
  args:
    chdir: "{{ docker_compose_dir }}"

- name: create compass db tables
  shell: |
    docker exec compass-deck bash -c "/opt/compass/bin/manage_db.py createdb"
  tags:
    - redploy

- name: replace cobbler.conf
  shell: |
    docker cp "{{ docker_compose_dir }}/os_installer/cobbler.conf" \
    compass-tasks:/etc/compass/os_installer/; \
    docker cp "{{ docker_compose_dir }}/os_installer/cobbler.conf" \
    compass-deck:/etc/compass/os_installer/

- name: cp ansible dir
  shell: |
    docker exec compass-tasks bash -c \
    "cp -rf /root/ansible /var; \
     mkdir -p /var/ansible/run"

#- name: cp ansible_modules
#  shell: |
#    docker exec compass-tasks bash -c \
#    "cp -rf /var/ansible/ansible_modules /opt/ansible-modules"
